eureka:
  client:
    register-with-eureka: true

server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: partners
          uri: lb://PARTNERS-SERVICE # Utilisation de lb:// pour l'équilibrage de charge via Ribbon
          predicates:
            - Path=/partners/**
