eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9102/eureka/
server:
  port: 9106

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Microservice-partner
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
